# Generated by Django 4.0.3 on 2022-04-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_descricao', models.CharField(max_length=200, verbose_name='Curso')),
                ('graduacao', models.CharField(max_length=200, verbose_name='Graduação')),
                ('modalidade', models.CharField(max_length=200, verbose_name='Modalidade')),
                ('imagem', models.CharField(max_length=1000, verbose_name='Caminho da Imagem')),
                ('link_faesa', models.CharField(max_length=1000, verbose_name='Link Faesa')),
            ],
        ),
    ]
